# Generated by Django 4.2 on 2024-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('text_article', models.CharField(max_length=5000)),
                ('accept', models.BooleanField(default=False)),
                ('date_of_publicate', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='articles.category')),
            ],
        ),
    ]
